### ISSUE TITLE
Linting Gulpfile.js

### ISSUE THREAD

**Issue by 0liver** [Lombiq/Gulp-Extensions#20]
Having ESLint in place, wouldn't it be consequent to run it on the Gulpfile itself, too?

This would help keep the Gulpfile clean and adhere to the same (strict) rules we use everywhere else.

**Comment by Piedone** [comment]
I don't think we can run the Gulpfile, that described the Gulp pipeline, through the same Gulp pipeline. However, if you set up the project as documented, then you'll get ESLint warnings in the IDE for the Gulpfile too.

**Comment by Piedone** [comment]
Now with [recommended setups](https://github.com/Lombiq/Gulp-Extensions#tips-for-using-and-naming-multiple-gulp-tasks) this should be less of an issue since most Gulpfiles can be two lines.

I guess we could have a task that just lints ./Gulpfile.js.

**Comment by Piedone** [comment]
We won't continue developing this project.
